services:
  spotiflac-bot:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: spotiflac-telegram-bot

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./data/downloads:/app/downloads
      - ./data/spotiflac:/home/spotiflac/.spotiflac

    environment:
      SPOTIFLAC_REGISTRIES: "https://raw.githubusercontent.com/spotiflacapp/SpotiFLAC-Extension/main/registry.json"

    stop_grace_period: 30s
