services:
  spotiflac-bot:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: spotiflac-telegram-bot

    restart: unless-stopped

    env_file:
      - .env

    environment:
      SPOTIFLAC_REGISTRIES: "https://raw.githubusercontent.com/spotiflacapp/SpotiFLAC-Extension/main/registry.json"
      DISPLAY: ":99"
      TS_DEBUG_VISIBLE: "1"

    volumes:
      - ./data/downloads:/app/downloads
      - ./data/spotiflac:/home/spotiflac/.spotiflac
      - ./data/cache:/home/spotiflac/.cache/spotiflac

    shm_size: "1gb"

    stop_grace_period: 30s
